# Generated by Django 6.0.8 on 2026-09-28 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('estado', models.CharField(choices=[('nuevo', 'nuevo'), ('contactado', 'contactado'), ('convertido', 'convertido'), ('descartado', 'descartado')], default='nuevo', max_length=20, verbose_name='estado')),
                ('formato', models.CharField(help_text='Source adapter that parsed the submission.', max_length=30, verbose_name='formato')),
                ('origen', models.CharField(max_length=50, verbose_name='origen')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('servicio_interes', models.CharField(blank=True, max_length=100, verbose_name='servicio de interés')),
                ('plan', models.CharField(blank=True, max_length=50, verbose_name='plan')),
                ('servicio_desconocido', models.BooleanField(default=False, help_text='A service was given but is not in the catalogue.', verbose_name='servicio desconocido')),
                ('plan_desconocido', models.BooleanField(default=False, help_text='A plan was given but is not in the catalogue.', verbose_name='plan desconocido')),
                ('mensaje', models.TextField(blank=True, verbose_name='mensaje')),
                ('recibido_en', models.DateTimeField(verbose_name='recibido en')),
                ('payload_original', models.JSONField(verbose_name='payload original')),
                ('dedup_key', models.CharField(editable=False, max_length=64, unique=True, verbose_name='clave de deduplicación')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospectos', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'prospecto',
                'verbose_name_plural': 'prospectos',
                'ordering': ['-recibido_en'],
            },
        ),
    ]
