# Generated by Django 6.0.8 on 2026-09-20 22:57

import crm_easyoffice.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('rut', models.CharField(help_text='Without dots and with a hyphen, for example 76543210-K.', max_length=12, unique=True, validators=[crm_easyoffice.core.validators.validate_rut], verbose_name='RUT')),
                ('razon_social', models.CharField(max_length=255, verbose_name='razón social')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=255, verbose_name='nombre de fantasía')),
                ('giro', models.CharField(blank=True, max_length=255, verbose_name='giro')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('rut', models.CharField(help_text='Without dots and with a hyphen, for example 12345678-5.', max_length=12, unique=True, validators=[crm_easyoffice.core.validators.validate_rut], verbose_name='RUT')),
                ('nombres', models.CharField(max_length=100, verbose_name='nombres')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, verbose_name='apellido materno')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('empresa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='clientes.empresa', verbose_name='empresa')),
                ('persona', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='clientes.persona', verbose_name='persona')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('empresa__isnull', True), ('persona__isnull', False)), models.Q(('empresa__isnull', False), ('persona__isnull', True)), _connector='OR'), name='cliente_exactamente_una_parte')],
            },
        ),
        migrations.CreateModel(
            name='RepresentanteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('vigente_desde', models.DateField(verbose_name='vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, help_text='Empty means the representation has no end date.', null=True, verbose_name='vigente hasta')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='representantes', to='clientes.empresa', verbose_name='empresa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='representaciones', to='clientes.persona', verbose_name='persona')),
            ],
            options={
                'verbose_name': 'representante legal',
                'verbose_name_plural': 'representantes legales',
                'ordering': ['-vigente_desde'],
                'constraints': [models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gt', models.F('vigente_desde')), _connector='OR'), name='representante_periodo_valido')],
            },
        ),
    ]
