# Generated by Django 6.0.8 on 2026-09-20 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('rol_avaluo', models.CharField(help_text='Property tax roll number assigned by the SII.', max_length=20, unique=True, verbose_name='rol de avalúo')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('calle', models.CharField(max_length=255, verbose_name='calle')),
                ('numero', models.CharField(max_length=20, verbose_name='número')),
                ('unidad', models.CharField(blank=True, help_text='Office or apartment number, when applicable.', max_length=20, verbose_name='unidad')),
                ('comuna', models.CharField(max_length=100, verbose_name='comuna')),
                ('region', models.CharField(max_length=100, verbose_name='región')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'oficina',
                'verbose_name_plural': 'oficinas',
                'ordering': ['region', 'comuna', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('vigente_desde', models.DateField(verbose_name='vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, help_text='Empty means the domicile has no end date.', null=True, verbose_name='vigente hasta')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domicilios', to='clientes.empresa', verbose_name='empresa')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='inmuebles.oficina', verbose_name='oficina')),
            ],
            options={
                'verbose_name': 'asignación de domicilio',
                'verbose_name_plural': 'asignaciones de domicilio',
                'ordering': ['-vigente_desde'],
                'constraints': [models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gt', models.F('vigente_desde')), _connector='OR'), name='domicilio_periodo_valido')],
            },
        ),
    ]
